name: Hakukohderyhmapalvelu

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up JDK 11
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          java-version: '11'
          distribution: 'corretto'

      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6
        name: Install pnpm

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: latest

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@4c7a6f613e5089821bb3bb2a33a3ee115578580d # 13.6.1
        with:
          lein: 2.9.3

      - uses: szenius/set-timezone@1f9716b0f7120e344f0c62bb7b1ee98819aefd42 # v2.0
        with:
          timezoneLinux: "Europe/Helsinki"

      # Remove following in the future (and update script in package.json), it installs chrome version 116 as the current 117 has bug
      - uses: browser-actions/setup-chrome@48ad923757ca74d66703209fe939badbdf80f2f4 # v2
        with:
            chrome-version: 1160321
        id: setup-chrome
      - run: |
          echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
          echo Installed chromium path: ${{ steps.setup-chrome.outputs.chrome-path }}
          which chromium
          chromium --version
          

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm install
          ./bin/cibuild.sh run-all-tests-and-create-uberjar

      - name: Archive test results
        if: success() || failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: test-snapshots
          path: cypress/screenshots
          retention-days: 4

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        id: ci-tools
        with:
          path: ci-tools
          key: ${{ github.sha }}

  deploy-container:
    needs: [build]
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: hakukohderyhmapalvelu
      base-image: baseimage-fatjar-openjdk11:master
      configfolder: oph-configuration
      jarfile: hakukohderyhmapalvelu
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}

  deploy-ovara-container:
    needs: [ build ]
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: ovara-hakukohderyhmapalvelu
      base-image: baseimage-fatjar-openjdk11:master
      configfolder: ovara-oph-configuration
      jarfile: ovara-hakukohderyhmapalvelu
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
